Update demohelloword.yml

diff --git a/.github/workflows/demohelloword.yml b/.github/workflows/demohelloword.yml
--- a/.github/workflows/demohelloword.yml
+++ b/.github/workflows/demohelloword.yml
@@ -1,13 +1,23 @@
 name: hello-world
 'on': push
 jobs:
-  my-job:
+  build-test:
+    name: Build & Test
     runs-on: ubuntu-latest
     steps:
-      - name: my-step
-        run: echo "Hello World!"
-      - name: HTML Preview
-        id: html_preview
-        uses: htmlpreview/htmlpreview.github.com@v2
+      - uses: actions/checkout@v2     # checkout the repo
+      - run: npm ci                   # install packages
+      - run: npm test                 # run tests (configured to use jest-junit reporter)
+
+      - name: Test Report
+        uses: phoenix-actions/test-reporting@v8
+        id: test-report               # Set ID reference for step
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          html_file: 'index.html'
+          name: JEST Tests            # Name of the check run which will be created
+          path: reports/jest-*.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
+
+      - name: Read output variables
+        run: |
+          echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
